### ISSUE TITLE
Seek text on loop

### ISSUE THREAD

**Issue by blacki** [OpenframeProject/Openframe-Video#1]
When video loops timestamp seek text is displayed. `omxplayer --loop  video.mp4` doesn't do this by default.

**Comment by jmwohl** [comment]
I noticed this too — I think the compiled version of omxplayer that gets installed on the Pi via apt-get _does_ do this by default, since the only other [flags we're adding](https://github.com/OpenframeProject/Openframe-Video/blob/master/extension.js#L23-L27) are the --aspect-mode and -b. 

I'll take a look at the omxplayer docs and see if there is a quiet mode, or maybe we can just do the ol' trick: `> /dev/null 2>&1`.

**Comment by jmwohl** [comment]
This is fixed in the latest release. Note that very short videos don't loop as expected with omxplayer.
